import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { withAuthenticator, AmplifySignOut } from '@aws-amplify/ui-react'
import { Amplify, API, graphqlOperation } from 'aws-amplify';
import aws_exports from '../src/aws-exports';
import { getTodo, listTodos, recfunction } from '../src/graphql/queries'
import { createTodo, updateTodo, deleteTodo } from '../src/graphql/mutations'
import { useEffect, useState } from 'react';
import { GraphQLResult } from '@aws-amplify/api-graphql';
import Observable from 'zen-observable-ts';
Amplify.configure(aws_exports);

interface Person {
  recfunction: string;
}

const initialState: Person = { recfunction: 'Empty' };

const Home: NextPage = () => {
  const [data, setData] = useState(initialState)

  function callRecFunction() {
    const prm = (API.graphql(graphqlOperation(recfunction, { msg: "test" })) as Promise<GraphQLResult>);
    prm
      .then((res) => {
        //console.log(res);
        return res.data as Person;
      })
      .then((res) => {
        console.log(res);
        setData({ recfunction: res.recfunction });
        return res;
      })
  }

  return (
    <div className={styles.container}>
      <AmplifySignOut />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={() => callRecFunction()}>
          Click me
        </button>

        <p className={styles.description}>{data.recfunction}</p>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default withAuthenticator(Home)
